openapi: 3.1.0
info:
  version: 1.0.0
  title: Aqautrack App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation for the water tracking web service
tags:
  - name: Auth
    description: Auth operations.
  - name: Water
    description: Water operations.
servers:
  - url: http://localhost:3001
  - url: aquatrack-project-backend.onrender.com
paths:
  /auth/signup:
    post:
      $ref: ../swagger/paths/users/signup.yaml
  /auth/signin:
    post:
      $ref: ../swagger/paths/users/signin.yaml
  /auth/current:
    get:
      $ref: ../swagger/paths/users/{id}/get.yaml
  /auth/update/{userId}:
    patch:
      $ref: ../swagger/paths/users/{id}/patch.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/users/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/users/refresh.yaml
  /auth/users:
    get:
      $ref: ../swagger/paths/users/getAllUsers.yaml
  /auth/request-reset-email:
    post:
      $ref: ../swagger/paths/users/requestResetEmail.yaml
  /auth/reset-password:
    post:
      $ref: ../swagger/paths/users/resetPassword.yaml
  /auth/confirm-google-auth:
    post:
      $ref: ../swagger/paths/users/confirmGoogleAuth.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/users/getGoogleOAuthUrl.yaml

  /water:
    post:
      $ref: ../swagger/paths/water/createWater.yaml
  /water/{waterId}:
    put:
      $ref: ../swagger/paths/water/{id}/updateWater.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/deleteWater.yaml
  /water/perDay:
    get:
      $ref: ../swagger/paths/water/getWaterPerDay.yaml
  /water/perMonth:
    get:
      $ref: ../swagger/paths/water/getWaterPerMonth.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
