openapi: 3.1.0
info:
  version: 1.0.0
  title: Aqautrack App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation for the water tracking web service
tags:
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3001
  - url: aquatrack-project-backend.onrender.com
paths:
  /auth/signup:
    post:
      $ref: ../swagger/paths/users/signup.yaml
  /auth/signin:
    post:
      $ref: ../swagger/paths/users/signin.yaml
  /auth/{userId}:
    get:
      $ref: ../swagger/paths/users/{id}/get.yaml
  /auth/update/{userId}:
    patch:
      $ref: ../swagger/paths/users/{id}/patch.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/users/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/users/refresh.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
